export const AUTHENTICATE_USER = 'AUTHENTICATE_USER';
export const UNAUTHENTICATE_USER = 'UNAUTHENTICATE_USER';

export const GET_ALL_EVENTS_SUCCESS = 'GET_ALL_EVENTS_SUCCESS';
export const CREATE_EVENT_SUCCESS = 'CREATE_EVENT_SUCCESS';

export const GET_USER_DETAILS_SUCCESS = 'GET_USER_DETAILS_SUCCESS';

export const API_START = 'API_START';
export const API_DONE = 'API_DONE';
